# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listViewProducts = QtWidgets.QListView(self.centralwidget)
        self.listViewProducts.setGeometry(QtCore.QRect(40, 70, 581, 451))
        self.listViewProducts.setObjectName("listViewProducts")
        self.pushButtonAddItem = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddItem.setGeometry(QtCore.QRect(510, 10, 131, 41))
        self.pushButtonAddItem.setStyleSheet("font-size: 8pt;\n"
"")
        self.pushButtonAddItem.setObjectName("pushButtonAddItem")
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(210, 10, 131, 41))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setGeometry(QtCore.QRect(360, 10, 131, 41))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.pushButtonRemove = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRemove.setGeometry(QtCore.QRect(660, 10, 131, 41))
        self.pushButtonRemove.setStyleSheet("font-size: 8pt;\n"
"")
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEdit.setGeometry(QtCore.QRect(810, 10, 131, 41))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.labelStatisticCountFood = QtWidgets.QLabel(self.centralwidget)
        self.labelStatisticCountFood.setGeometry(QtCore.QRect(40, 520, 171, 61))
        self.labelStatisticCountFood.setStyleSheet("font-size: 12pt;\n"
"")
        self.labelStatisticCountFood.setObjectName("labelStatisticCountFood")
        self.listViewDish = QtWidgets.QListView(self.centralwidget)
        self.listViewDish.setGeometry(QtCore.QRect(650, 230, 621, 461))
        self.listViewDish.setObjectName("listViewDish")
        self.pushButtonShowStatistics = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonShowStatistics.setGeometry(QtCore.QRect(960, 10, 161, 41))
        self.pushButtonShowStatistics.setObjectName("pushButtonShowStatistics")
        self.labelCheckAmountOfProducts = QtWidgets.QLabel(self.centralwidget)
        self.labelCheckAmountOfProducts.setGeometry(QtCore.QRect(860, 90, 111, 16))
        self.labelCheckAmountOfProducts.setStyleSheet("font-size: 12pt")
        self.labelCheckAmountOfProducts.setObjectName("labelCheckAmountOfProducts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAddItem.setText(_translate("MainWindow", "Додати"))
        self.pushButtonSave.setText(_translate("MainWindow", "Зберегти"))
        self.pushButtonLoad.setText(_translate("MainWindow", "Завантажити"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Видалити"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Редагувати"))
        self.labelStatisticCountFood.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonShowStatistics.setText(_translate("MainWindow", "Переглянути статистику"))
        self.labelCheckAmountOfProducts.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
