# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainProgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listViewProducts = QtWidgets.QListView(self.centralwidget)
        self.listViewProducts.setGeometry(QtCore.QRect(40, 70, 581, 441))
        self.listViewProducts.setObjectName("listViewProducts")
        self.pushButtonAddProduct = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddProduct.setGeometry(QtCore.QRect(240, 520, 231, 51))
        self.pushButtonAddProduct.setStyleSheet("font-size: 16pt;\n"
"")
        self.pushButtonAddProduct.setObjectName("pushButtonAddProduct")
        self.pushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(520, 10, 93, 28))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setGeometry(QtCore.QRect(620, 10, 93, 28))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.pushButtonAddDish = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddDish.setGeometry(QtCore.QRect(870, 160, 231, 51))
        self.pushButtonAddDish.setStyleSheet("font-size: 16pt;\n"
"")
        self.pushButtonAddDish.setObjectName("pushButtonAddDish")
        self.pushButtonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEdit.setGeometry(QtCore.QRect(720, 10, 93, 28))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.labelStatistic = QtWidgets.QLabel(self.centralwidget)
        self.labelStatistic.setGeometry(QtCore.QRect(970, 70, 171, 61))
        self.labelStatistic.setObjectName("labelStatistic")
        self.listViewDish = QtWidgets.QListView(self.centralwidget)
        self.listViewDish.setGeometry(QtCore.QRect(690, 230, 621, 461))
        self.listViewDish.setObjectName("listViewDish")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAddProduct.setText(_translate("MainWindow", "Додати продукт"))
        self.pushButtonSave.setText(_translate("MainWindow", "Зберегти"))
        self.pushButtonLoad.setText(_translate("MainWindow", "Завантажити"))
        self.pushButtonAddDish.setText(_translate("MainWindow", "Додати страву"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Редагувати"))
        self.labelStatistic.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
