# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import mysql.connector

from PyQt5 import QtCore, QtGui, QtWidgets
from mainProgram.MainProgram import Ui_MainWindow

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(468, 527)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 85, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.labelLogin = QtWidgets.QLabel(Dialog)
        self.labelLogin.setGeometry(QtCore.QRect(170, 50, 121, 61))
        self.labelLogin.setStyleSheet("font-size:28pt;\n"
"background-color:none;")
        self.labelLogin.setObjectName("labelLogin")
        self.loginLabelEmail = QtWidgets.QLabel(Dialog)
        self.loginLabelEmail.setGeometry(QtCore.QRect(50, 149, 71, 31))
        self.loginLabelEmail.setStyleSheet("font-size:15pt;\n"
"background: none;\n"
"")
        self.loginLabelEmail.setObjectName("loginLabelEmail")
        self.loginLabelPassword = QtWidgets.QLabel(Dialog)
        self.loginLabelPassword.setGeometry(QtCore.QRect(50, 229, 111, 31))
        self.loginLabelPassword.setStyleSheet("font-size:15pt;\n"
"background: none;")
        self.loginLabelPassword.setObjectName("loginLabelPassword")
        self.loginLineEditEmail = QtWidgets.QLineEdit(Dialog)
        self.loginLineEditEmail.setGeometry(QtCore.QRect(190, 150, 221, 31))
        self.loginLineEditEmail.setStyleSheet("font-size:15pt\n"
"")
        self.loginLineEditEmail.setObjectName("loginLineEditEmail")
        self.loginLineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.loginLineEditPassword.setGeometry(QtCore.QRect(190, 230, 221, 31))
        self.loginLineEditPassword.setStyleSheet("font-size:15pt")
        self.loginLineEditPassword.setObjectName("loginLineEditPassword")
        self.pushButtonOpenRegMenu = QtWidgets.QPushButton(Dialog)
        self.pushButtonOpenRegMenu.setGeometry(QtCore.QRect(250, 320, 121, 28))
        self.pushButtonOpenRegMenu.setStyleSheet("background: transparent;\n"
"color: rgb(0, 0, 127);\n"
"font-size:9pt;")
        self.pushButtonOpenRegMenu.setObjectName("pushButtonOpenRegMenu")
        self.pushButtonOpenRegMenu.clicked.connect(lambda: self.open_registration_dialog(Dialog))
        self.pushButtonLogin = QtWidgets.QPushButton(Dialog)
        self.pushButtonLogin.setGeometry(QtCore.QRect(140, 410, 161, 41))
        self.pushButtonLogin.setStyleSheet("font-size:16pt;")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.justLabel = QtWidgets.QLabel(Dialog)
        self.justLabel.setGeometry(QtCore.QRect(70, 320, 171, 31))
        self.justLabel.setStyleSheet("font-size:10pt;\n"
"background: none;")
        self.justLabel.setObjectName("justLabel")
        self.pushButtonLogin.clicked.connect(self.open_main_window)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.db_connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="admin",
            database="AuthorizationDB"
        )
        self.cursor = self.db_connection.cursor()
    def open_main_window(self):
        self.main_window = QtWidgets.QMainWindow()
        self.ui_main_window = Ui_MainWindow()
        self.ui_main_window.setupUi(self.main_window)
        self.main_window.show()
        # Close the current login dialog
        Dialog.close()
    def open_registration_dialog(self, Dialog):
        self.dialog = QtWidgets.QDialog()
        self.ui = Registration.Ui_RegistrationDialog()
        self.ui.setupUi(self.dialog)
        self.dialog.show()
        Dialog.close()

    def login(self):
        email = self.loginLineEditEmail.text()
        password = self.loginLineEditPassword.text()

        # Check if the user exists in the database
        self.cursor.execute("SELECT * FROM users WHERE email = %s AND password = %s", (email, password))
        user = self.cursor.fetchone()
        if user:
            QtWidgets.QMessageBox.information(None, "Success", "Login successful!")
        else:
            QtWidgets.QMessageBox.warning(None, "Error", "Invalid email or password.")
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelLogin.setText(_translate("Dialog", "Login"))
        self.loginLabelEmail.setText(_translate("Dialog", "Email"))
        self.loginLabelPassword.setText(_translate("Dialog", "Password"))
        self.pushButtonOpenRegMenu.setText(_translate("Dialog", "Зареєструватись"))
        self.pushButtonLogin.setText(_translate("Dialog", "Увійти"))
        self.justLabel.setText(_translate("Dialog", "No Account? Create it:"))





import Registration
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
